### ISSUE TITLE
Typed Declaration

### ISSUE THREAD

**Issue by Maxwell-Alexius** [Maxwell-Alexius/Wyrd#114]
**What?**
Change all assignment declaration into `Typed` declaration.

**Why?**
Since Wyrd is a strongly typed language, it is weird that the constant declaration's type is based on the evaluated expression on the right-side of the `eq` token:

```
# `foo` is declared as a constant with type `Str`
foo = (123 + 456).toStr()
```

**How?**
When declaring constants, it is better to declare the type first and check the left-side of the assigned type of the constant is equal to the right-side evaluated expression's type:

```
Str foo = (123 + 456).toStr()
```

Also, mutable variable declaration can be addressed with `mutable` keyword:

```
mutable Str bar = (123 + 456).toStr()
```

When declaring `maybe` types, we can now change it into:

```
mutable maybe Str baz = (123 + 456).toStr()
```

or, if the default value of the `maybe` types is `Null`, we can omit the `eq` token:

```
mutable maybe Str bazz
```

The advantage of this is that, when we are entering child scopes, e.g. conditional expressions, we can distinguish between calling variables from outer scope or declaring new variable in child scope:

```
mutable Num foo = 123
baz = if <cond> do
       foo = 456
       foo
     else do
       # using typed declaration
       Num foo = 123
       foo + 456
     end

# if <cond> is True, `foo` is mutated to 456, `baz` is 456
# if <cond> is False, `foo` isn't mutated, while `baz` is 123 + 456 = 579
foo
```

**TODO**
- [x] Typed constant declaration
- [x] Typed mutable variable declaration
- [x] Typed mutable `maybe` types variable declaration

**Comment by Maxwell-Alexius** [comment]
Completed in #115 and #117
